# Generated by Django 4.0.3 on 2022-08-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_auto_20220806_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
