# Generated by Django 4.0.3 on 2022-08-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0005_auto_20220821_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
