# Generated by Django 4.0.3 on 2022-08-26 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circleprogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField(default='', null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('hashtag', models.TextField(max_length=100)),
                ('apply', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circleprogram', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
                ('circleprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuprogram.circleprogram')),
            ],
        ),
    ]
