# Generated by Django 4.0.3 on 2022-08-26 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kuprogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleprogram',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circleprogram', to=settings.AUTH_USER_MODEL),
        ),
    ]
