# Generated by Django 4.0.3 on 2022-08-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuprogram', '0002_alter_circleprogram_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleprogram',
            name='inquiry',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
