# Generated by Django 4.0.3 on 2022-08-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuprogram', '0003_circleprogram_inquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
