# Generated by Django 4.0.3 on 2022-09-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='coorx',
        ),
        migrations.RemoveField(
            model_name='program',
            name='coory',
        ),
        migrations.RemoveField(
            model_name='program',
            name='type',
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
