# Generated by Django 4.0.3 on 2022-09-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_remove_program_coorx_remove_program_coory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
