# Generated by Django 4.0.3 on 2022-08-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_program_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_list', models.CharField(max_length=10, verbose_name='category_list')),
            ],
        ),
    ]
