# Generated by Django 4.0.3 on 2022-09-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_alter_program_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='age',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
