# Generated by Django 4.0.3 on 2022-08-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_category_delete_category_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='coorx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='coory',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.IntegerField(),
        ),
    ]
