# Generated by Django 4.0.3 on 2022-09-22 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0004_alter_program_age_alter_program_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='like_users_p',
            field=models.ManyToManyField(related_name='like_programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
