# Generated by Django 4.0.3 on 2022-09-22 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0005_program_like_users_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='like_users_p',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
