# Generated by Django 4.0.3 on 2022-08-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_program_coorx_program_coory_program_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='coorx',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='coory',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
