# Generated by Django 4.0.3 on 2022-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_alter_program_coorx_alter_program_coory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='link',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
