# Generated by Django 4.0.3 on 2022-09-22 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0006_alter_program_like_users_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='like_users_p',
        ),
        migrations.AddField(
            model_name='program',
            name='like_users',
            field=models.ManyToManyField(related_name='like_program', to=settings.AUTH_USER_MODEL),
        ),
    ]
