# Generated by Django 4.0.3 on 2022-08-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='recommendation1',
            new_name='rec1',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='recommendation2',
            new_name='rec2',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='recommendation3',
            new_name='rec3',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='recommendation4',
            new_name='rec4',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='rec1obj',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='rec2obj',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='rec3obj',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='rec4obj',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
