# Generated by Django 4.0.3 on 2022-09-22 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ku_manam', '0004_article_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hits',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='like_users',
            field=models.ManyToManyField(related_name='like_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
