# Generated by Django 4.0.3 on 2022-09-22 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ku_manam', '0005_remove_question_hits_question_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_users',
            field=models.ManyToManyField(related_name='like_community', to=settings.AUTH_USER_MODEL),
        ),
    ]
